
var doingLp = false;


function sAjax (url, data) {
                                                                                                                                                                                                                                                                                                                                                 
                try {                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                 
                        ajax = new XMLHttpRequest();                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                 
                } catch(err) {                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                 
                        ajax = new ActiveXObject("Microsoft.XMLHTTP");                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                 
                }                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                 
                if (ajax) {                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                 
                        ajax.open("POST", url, false);                                                                                                                                                                                                                                                                                           
                        ajax.setRequestHeader("Content-type", "application/json");                                                                                                                                                                                                                                                               
                        ajax.send(data);                                                                                                                                                                                                                                                                                                         
                        return ajax.responseText;                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                 
                } else {                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                 
                        return false;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                 
                }                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                 
}

function longPoll() {                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                 
        if (doingLp)                                                                                                                                                                                                                                                                                                                             
                return;                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                 
        doingLp = true;                                                                                                                                                                                                                                                                                                                          
        var request = {};                                                                                                                                                                                                                                                                                                                        
        request.method = 'getwork';                                                                                                                                                                                                                                                                                                              
        request.params = [];                                                                                                                                                                                                                                                                                                                     
        request.id = 0;                                                                                                                                                                                                                                                                                                                          
        var jsonResponse = sAjax('/lm/lp.php', JSON.stringify(request));                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                 
        // Get New Work                                                                                                                                                                                                                                                                                                                          
        doingLp = false;                                                                                                                                                                                                                                                                                                                         
	self.postMessage({'notification': "New Work from LP"}); 
 }                                                                                                                                                                                                                                                                                                                                               

while (true) {
	longPoll();
}
